# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  frontend:
    name: Frontend CI
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache dependencies
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.npm
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('kim_chat_frontend/**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-
          node-

    - name: Install dependencies
      run: |
        if [ ! -f "kim_chat_frontend/package-lock.json" ]; then
          echo "No lock file found in kim_chat_frontend. Generating one...";
          cd kim_chat_frontend && npm install --package-lock-only;
        fi
        cd kim_chat_frontend && npm ci

    - name: Build frontend
      run: cd kim_chat_frontend && npm run build --if-present

    - name: Run frontend tests
      run: cd kim_chat_frontend && npm test

  backend:
    name: Backend CI
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Cache dependencies
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.npm
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('kim_chat_backend/**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-
          node-

    - name: Install dependencies
      run: |
        if [ ! -f "kim_chat_backend/package-lock.json" ]; then
          echo "No lock file found in kim_chat_backend. Generating one...";
          cd kim_chat_backend && npm install --package-lock-only;
        fi
        cd kim_chat_backend && npm ci

    - name: Build backend
      run: cd kim_chat_backend && npm run build --if-present

    - name: Run backend tests
      run: cd kim_chat_backend && npm test
