# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  frontend:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.npm
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('kim_chat_frontend/**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-
          node-
    - run: cd kim_chat_frontend && npm ci
    - run: cd kim_chat_frontend && npm run build --if-present
    - run: cd kim_chat_frontend && npm test
    - run: |
        if [ ! -f "kim_chat_frontend/package-lock.json" ]; then
          echo "No lock file found in kim_chat_frontend. Running npm install to generate one.";
          cd kim_chat_frontend && npm install;
        fi

  backend:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x, 22.x]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Cache
      uses: actions/cache@v4.2.3
      with:
        path: |
          ~/.npm
          ~/.cache
        key: ${{ runner.os }}-node-${{ hashFiles('kim_chat_backend/**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          ${{ runner.os }}-
          node-
    - run: cd kim_chat_backend && npm ci
    - run: cd kim_chat_backend && npm run build --if-present
    - run: cd kim_chat_backend && npm test
    - run: |
        if [ ! -f "kim_chat_backend/package-lock.json" ]; then
          echo "No lock file found in kim_chat_backend. Running npm install to generate one.";
          cd kim_chat_backend && npm install;
        fi
